[platformio]
default_envs = feather-m4-can

[env:feather-m4-can]
platform = atmelsam
board = adafruit_feather_m4_can
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/adafruit/Adafruit_CAN.git
