### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Chummins_DashContent)
add_subdirectory(qml_imports)
add_subdirectory(App)
add_subdirectory(Dependencies)

qt6_add_resources(${CMAKE_PROJECT_NAME} MainResource
    PREFIX "/qt/qml"
    VERSION 1.0
    FILES 
        ".vscode/settings.json"
        ".vscode/c_cpp_properties.json"
        "firmware_waveshare/.pio/libdeps/waveshare-esp32s3-poe/ArduinoJson/library.json"
)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Chummins_DashContentplugin
    QtQuick_Studio_Componentsplugin
    QtQuickDesignerComponents)